# Site settings
title: State of the Map Asia - Asia Resilience Forum 2016
email: your-email@domain.com
description: "tag/theme or whatever blurb"
baseurl: ""
url: "http://sotm-asia.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
