# Site settings
title: State of the Map Asia - Asia Resilience Forum 2016
email: osmpilipinas+sotmasia2016@gmail.com
description: "tag/theme or whatever blurb"
baseurl: "/sotm-asia-2016-website"
url: "http://sotm-asia.com"
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: pretty
