# Site settings
title: State of the Map Asia - Asia Resilience Forum 2016
email: osmpilipinas+sotmasia2016@gmail.com
description: "tag/theme or whatever blurb"
#baseurl: "/"
url: "http://stateofthemap.asia/"
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: pretty
